services:
  modbus-slave:
    build:
      context: ./MasterSlave
      dockerfile: Dockerfile
    container_name: modbus-slave
    ports:
      - "502:502"
    networks:
      - modbus-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080

  modbus-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modbus-master
    depends_on:
      - modbus-slave
    networks:
      - modbus-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      
  user-inputs:
    build:
        context: ./UserInputs
        dockerfile: Dockerfile
    container_name: user-inputs
    ports:
        - "5181:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development

networks:
  modbus-network:
    driver: bridge